-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.budget
(
    budget_id integer NOT NULL DEFAULT nextval('budget_budget_id_seq'::regclass),
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    amount money NOT NULL,
    month integer NOT NULL,
    year integer NOT NULL,
    CONSTRAINT budget_pkey PRIMARY KEY (budget_id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id integer NOT NULL DEFAULT nextval('category_category_id_seq'::regclass),
    category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (category_id),
    CONSTRAINT category_category_name_key UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.goal
(
    goal_id integer NOT NULL DEFAULT nextval('goal_goal_id_seq'::regclass),
    user_id integer NOT NULL,
    goal_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    target_amount money NOT NULL,
    current_amount money DEFAULT 0.00,
    deadline_date date NOT NULL,
    CONSTRAINT goal_pkey PRIMARY KEY (goal_id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    transaction_id integer NOT NULL DEFAULT nextval('transactions_transaction_id_seq'::regclass),
    user_id integer NOT NULL,
    amount money NOT NULL,
    category_id integer NOT NULL,
    description text COLLATE pg_catalog."default",
    transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hash_password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    profile_picture character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_id_key UNIQUE (email_id)
);

ALTER TABLE IF EXISTS public.budget
    ADD CONSTRAINT budget_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budget
    ADD CONSTRAINT budget_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.goal
    ADD CONSTRAINT goal_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;